# -*- coding: utf-8 -*-
"""Project_10_Chemical_solubility_predictor.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzU9L7M8Q4HphVUOWvphHDIhdvml48sc
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# 1. Create a dummy chemical dataset for demonstration
data = {
    'Compound': ['Ethanol', 'Benzene', 'Aspirin', 'Caffeine', 'Ibuprofen', 'Glucose'],
    'MolecularWeight': [46.07, 78.11, 180.16, 194.19, 206.29, 180.16],
    'LogP': [-0.18, 2.13, 1.19, -0.07, 3.50, -3.24],
    'LogS_Solubility': [-0.10, -2.74, -2.20, -1.15, -3.90, 0.40] # Target variable
}

df = pd.DataFrame(data)

# 2. Split features (X) and target (y)
X = df[['MolecularWeight', 'LogP']]
y = df['LogS_Solubility']

# FIX: Changed 'test_split' to 'test_size'
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Train the model
model = LinearRegression()
model.fit(X_train, y_train)

# 4. Predict and evaluate
y_pred = model.predict(X_test)
print("--- Model Evaluation ---")
print(f"Mean Squared Error: {mean_squared_error(y_test, y_pred):.4f}")
print(f"R2 Score: {r2_score(y_test, y_pred):.4f}\n")

# 5. Predict on a new virtual molecule
new_molecule = pd.DataFrame({'MolecularWeight': [150.0], 'LogP': [1.5]})
predicted_solubility = model.predict(new_molecule)

# FIX: Added [0] index to safely print the single predicted value from the array
print(f"Predicted LogS Solubility for Virtual Compound: {predicted_solubility[0]:.2f}")