# -*- coding: utf-8 -*-
"""Project_9_Chemical_lipinski_checker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AzU9L7M8Q4HphVUOWvphHDIhdvml48sc
"""

def check_lipinski(mw, logp, hbd, hba):
    """
    Evaluates a compound based on Lipinski's Rule of 5.
    """
    violations = 0
    report = []

    if mw > 500:
        violations += 1
        report.append(f"❌ Failed: Molecular Weight ({mw} Da) is > 500")
    else:
        report.append(f"✅ Passed: Molecular Weight ({mw} Da) is <= 500")

    if logp > 5:
        violations += 1
        report.append(f"❌ Failed: LogP ({logp}) is > 5")
    else:
        report.append(f"✅ Passed: LogP ({logp}) is <= 5")

    if hbd > 5:
        violations += 1
        report.append(f"❌ Failed: Hydrogen Bond Donors ({hbd}) > 5")
    else:
        report.append(f"✅ Passed: Hydrogen Bond Donors ({hbd}) <= 5")

    if hba > 10:
        violations += 1
        report.append(f"❌ Failed: Hydrogen Bond Acceptors ({hba}) > 10")
    else:
        report.append(f"✅ Passed: Hydrogen Bond Acceptors ({hba}) <= 10")

    is_drug_like = violations <= 1
    return is_drug_like, violations, report

# Example Test Case: Aspirin vs an Analog
compound_name = "Aspirin"
mol_wt = 180.16
log_p = 1.2
hb_donors = 1
hb_acceptors = 4

print(f"--- Analyzing Compound: {compound_name} ---")
is_drug, total_violations, detailed_report = check_lipinski(mol_wt, log_p, hb_donors, hb_acceptors)

for line in detailed_report:
    print(line)

print(f"\nConclusion: {'APPROVED' if is_drug else 'REJECTED'} as a drug candidate ({total_violations} violations).")